Actors:
- Id: 1
  Max_inventory: 60
  Name: Retailer
  Products:
  - Composition:
      '1002': 2
      '2001': 1
    Name: ProductA
    id: 1001
    initial_stock: 10
    safety_stock: 2
  - Composition:
      '1001': 100
      '2001': 12
    Name: ProductAB
    id: 1002
    initial_stock: 100
    safety_stock: 2
  Reorder_history_size: 7
  Time_Average: 1
  Time_variance: 1
- Id: 2
  Max_inventory: 60
  Name: Distributor
  Products:
  - Composition:
      '3001': 1
    Name: ProductB
    id: 2001
    initial_stock: 10
    safety_stock: 4
  Reorder_history_size: 7
  Time_Average: 1
  Time_variance: 1
- Id: 3
  Max_inventory: 60
  Name: Factory
  Products:
  - Composition:
      '4001': 1
    Name: ProductC
    id: 3001
    initial_stock: 15
    safety_stock: 5
  Reorder_history_size: 7
  Time_Average: 1
  Time_variance: 1
- Id: 4
  Max_inventory: 60
  Name: Raw Material Supplier
  Products:
  - Composition:
      '5001': 1
    Name: ProductD
    id: 4001
    initial_stock: 5
    safety_stock: 2
  Reorder_history_size: 7
  Time_Average: 1
  Time_variance: 1
- Id: 5
  Max_inventory: 60
  Name: Base Raw Material supplier
  Products:
  - Name: ProductE
    id: 5001
    initial_stock: 9999999999
    safety_stock: 1
  Reorder_history_size: 7
  Time_Average: 1
  Time_variance: 1
