docker run -it --rm \
  --network web_default \
  --name bullwhip-mongo-express \
  -p 8081:8081 \
  -e ME_CONFIG_OPTIONS_EDITORTHEME="ambiance" \
  -e ME_CONFIG_MONGODB_SERVER="web_db_1" \
  -e ME_CONFIG_BASICAUTH_USERNAME="user" \
  -e ME_CONFIG_BASICAUTH_PASSWORD="1234" \
  -e ME_CONFIG_MONGODB_PORT=2021\
  mongo-express